language: c

sudo: required

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq gfortran-5
  - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-5 90
  
before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: make
