name = "nonlin"
version = "1.5.2"
license = "GPL-3.0"
author = "Jason Christopherson"
maintainer = "Jason Christopherson"
copyright = "Copyright 2017-2024, Jason Christopherson"
description = "A library that provides routines to compute the solutions to systems of nonlinear equations."
homepage = "https://github.com/jchristopherson/nonlin"

[library]
source-dir = "src"

[dependencies]
ferror = { git = "https://github.com/jchristopherson/ferror" }
linalg = { git = "https://github.com/jchristopherson/linalg" }

[dev-dependencies]
fortran_test_helper = { git = "https://github.com/jchristopherson/fortran_test_helper" }

[install]
library = true

[build]
link = ["blas", "lapack"]
auto-executables = false
auto-examples = false
auto-tests = false

[[test]]
name = "nonlin_test"
source-dir = "tests"
main = "nonlin_test.f90"