name: doc-deployment

on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -v ford==6.1.17

    - name: Build Documentation
      run: ford docs.md

    - uses: JamesIves/github-pages-deploy-action@3.7.1
      if: github.event_name == 'push' && github.repository == 'jchristopherson/nonlin' && ( startsWith( github.ref, 'refs/tags/' ) || github.ref == 'refs/heads/master' )
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: doc
        CLEAN: true